// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct PoapScProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for PoapScProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = PoapScProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        PoapScProxyMethods { wrapped_tx: tx }
    }
}

pub struct PoapScProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> PoapScProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<EsdtTokenIdentifier<Env::Api>>,
    >(
        self,
        token_identifier: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&token_identifier)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> PoapScProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> PoapScProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn create_event<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<TimestampMillis>,
        Arg3: ProxyArg<u64>,
    >(
        self,
        name: Arg0,
        url: Arg1,
        end_date: Arg2,
        max_participants: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("createEvent")
            .argument(&name)
            .argument(&url)
            .argument(&end_date)
            .argument(&max_participants)
            .original_result()
    }

    pub fn claim_emblem<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        recipient: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("claimEmblem")
            .argument(&recipient)
            .original_result()
    }

    pub fn finalize_event(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("finalizeEvent")
            .original_result()
    }

    pub fn get_active_event_view<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        organizer: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<Event<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getActiveEvent")
            .argument(&organizer)
            .original_result()
    }

    pub fn has_claimed_view<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        event_id: Arg0,
        address: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("hasClaimed")
            .argument(&event_id)
            .argument(&address)
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone)]
pub struct Event<Api>
where
    Api: ManagedTypeApi,
{
    pub event_id: u64,
    pub name: ManagedBuffer<Api>,
    pub emblem_url: ManagedBuffer<Api>,
    pub start_date: TimestampMillis,
    pub end_date: TimestampMillis,
    pub is_stopped: bool,
    pub max_participants: u64,
    pub current_participants: u64,
    pub token_nonce: u64,
    pub organizer: ManagedAddress<Api>,
}
