// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    poap_sc
    (
        init => init
        upgrade => upgrade
        createEvent => create_event
        claimEmblem => claim_emblem
        finalizeEvent => finalize_event
        getActiveEvent => get_active_event_view
        hasClaimed => has_claimed_view
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
